apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinswebapi
  namespace: default
spec:
  selector:
    matchLabels:
      app: jenkinswebapi
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkinswebapi
    spec:
      containers:
      - name: jenkinswebapi
        image: abvirk/jenkinswebapi:replaceImageTag
        ports:
        - containerPort: 8080
