apiVersion: apps/v1
kind: Deployment
metadata:
  name: JenkinsWebApi
  namespace: default
spec:
  selector:
    matchLabels:
      app: JenkinsWebApi
  replicas: 1
  template:
    metadata:
      labels:
        app: JenkinsWebApi
    spec:
      containers:
      - name: JenkinsWebApi
        image: abvirk/jenkinswebapi:1
        ports:
        - containerPort: 8080
