apiVersion: v1
kind: Service
metadata:
  name: jenkinswebapi-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: jenkinswebapi
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
    nodePort: 30205
